### PR TITLE
Include bootstrap

### PR DESCRIPTION
**Pull request by weeman1337**
This PR adds bootstrap and sets up Hugo to build and include the scss files.

### CODE REVIEW

**Comment by mxmehl** [comment]
Thanks! It's the first time I see bootstrap included like this. So it seems this is included on the client side by running the npm commands, right? 

Is hosting these files statically in the repo discouraged?

**Comment by weeman1337** [comment]
> Is hosting these files statically in the repo discouraged?

Jep. Because if you patch these files (what is likely to happen with a probability near 1, if the files are in the repo) you cannot update it any more.

**Comment by weeman1337** [comment]
> So it seems this is included on the client side by running the npm commands, right?

No - the "end client" only receives the build files. Compare to the fsfe website.

**Comment by mxmehl** [comment]
Thanks for the info, I understand.

However, postcss-cli seemed to be missing on my side, I added it to the README and package.json. This cause also my package-lock.json to be different from your version, but I didn't commit it as I don't know how important it is.

**Comment by weeman1337** [comment]
I updated it again:
* I moved "postcss-cli" to the "devDependencies"
  Dev because it's only used for building/dev not for runtime (that is what "dependencies" is for)
* There is no need for listing every package in the readme. That's what the `package.json` is for. One `npm install` is enough.
* You should add the lock file to Git. The CI/Build system (and probably other developers)  then can install exactly the version you've worked with.

**Comment by mxmehl** [comment]
Ah, understood, thanks!

I'll merge it, but feel free to do that yourself for things you don't expect rebellion for ;)

**Pull request merged**
