### PR TITLE
Meta elements for social media

### LINKED ISSUE #25: improve social media preview
currently the preview of social media lacks the logo. 
also the "in Europe is double":

Selection_037

It should only say:
// foss.events
A collection of FOSS events in Europe

### PR DESCRIPTION
**Pull request by mxmehl**
Fixes #25.

Missing: we need a larger image, it should be at least 1000x1000px. @dreirik could you please create one?

It also renames a few files from floss -> foss. Please check if everything still works.

### CODE REVIEW

**Comment by weeman1337** [comment]
@mxmehl I'll add the SVG to the sources and a 1000px version as well

**Comment by weeman1337** [comment]
Done: https://github.com/flossevents/website/commit/f6f77575bd5645fc416937d801ddcf4c09914a54

**Comment by weeman1337** [comment]
I don't know whether this solves the Mastodon issue, but we give it a try

At least we now support Facebook and Twitter - it's floss :lol:

**Comment by mxmehl** [comment]
Mastodon should understand og and/or twitter meta elements, at least OpenGraph is rather standardised (Facebook uses it too, for instance)

Thanks @weeman1337

**Pull request merged**
